
## HIBERNATE
#hibernate.dialect.storage_engine=innodb
#spring.jpa.hibernate.ddl-auto=update

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#H2
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    password: sa
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2-console
#  jpa:
#    open-in-view: 'false'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: 'true'
#    show-sql: 'true'
#    hibernate:
#      ddl-auto: 'update'

##SUPABASE
#datasource:
#url: jdbc:postgresql://db.niocqzxypzutwctzuyfj.supabase.co:5432/postgres?user=postgres&password=c8-11-m-javaangular
#jpa:
#show-sql: true
#hibernate:
#ddl-auto: update

#LOCAL
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/todolist
    password: Lucas2205.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
port: 8080

jwt:
  secret: JWTSecretKey
  expiration: '604800000'
